let init = document.createElement("script");
let observe = document.createElement("script");
let proxy = document.createElement("script");
init.src = "../instrument/init.js";
observe.src = "../instrument/observe.js";
proxy.src = "../instrument/proxy.js";
document.head.appendChild(init);
document.head.appendChild(observe);
document.head.appendChild(proxy);
console.log("Proxy Ready");